POST http://127.0.0.1:5000/api/users/register
Content-Type: application/json

{
    "username": "Terry-4041",
    "password": "Terry-404"
}

###
POST http://127.0.0.1:5000/api/users/login
Content-Type: application/json

{
    "username": "Terry-404",
    "password": "Terry-404"
}

###
GET http://127.0.0.1:5000/api/users
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlcnJ5LTQwNCIsInBhc3N3b3JkIjoiVGVycnktNDA0IiwiaWF0IjoxNjQ1MDQzNzQyfQ.4Avw5D86w5q8weYLlQhfUwSh4tpSVc7rrC7A7OMUNk8
###

POST http://127.0.0.1:5000/api/users/links
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlcnJ5LTQwNCIsInBhc3N3b3JkIjoiVGVycnktNDA0IiwiaWF0IjoxNjQ1MDQzNzQyfQ.4Avw5D86w5q8weYLlQhfUwSh4tpSVc7rrC7A7OMUNk8

{
    "linkName": "testoqqo",
    "link": "https://example.com"
}

###
DELETE http://127.0.0.1:5000/api/users/links
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlcnJ5LTQwNCIsInBhc3N3b3JkIjoiVGVycnktNDA0IiwiaWF0IjoxNjM4NzA0ODA1fQ.OX0bhUM0b_S_UkvzXSKN6jfhhTqkhtFtmsTZdv7VqoU

{
    "linkName": "testoo"
}

###
PATCH http://127.0.0.1:5000/api/users/links
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlcnJ5LTQwNCIsInBhc3N3b3JkIjoiVGVycnktNDA0IiwiaWF0IjoxNjM4NzA0ODA1fQ.OX0bhUM0b_S_UkvzXSKN6jfhhTqkhtFtmsTZdv7VqoU

{
    "linkName": "Rick",
    "linkObj": {
        "linkName": "Rick-Roll",
        "link": "https://example.com"
        }
}

###
GET http://127.0.0.1:5000/logged
Content-Type: application/json
x-access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlcnJ5LTQwNCIsInBhc3N3b3JkIjoiVGVycnktNDA0IiwiaWF0IjoxNjM4NzA4MTQwfQ.YjX7-zVH77iuF0yeXpkbllMOxBx5-6e8ec0UVWvdjC8